services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=your-secure-secret-key-here
    networks:
      - onion_net
    restart: unless-stopped

  tor:
    image: osminogin/tor-simple:latest
    container_name: tornet_forum
    user: tor
    volumes:
      - ./tor/torrc:/etc/tor/torrc
    networks:
      - onion_net
    depends_on:
      - app
    restart: unless-stopped

networks:
  onion_net:
    driver: bridge
